version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app
      - ./nodemon.json:/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '8081'
    ports:
      - '80:8081'
    command: npm run dev